<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');



/**
 * APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:OzuFshjUMNIShJAKmX+vH7HHEQ4Qmb0AjYTf0jeXz2Y=
APP_DEBUG=true
APP_URL=http://localhost:8000

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=work_1
DB_USERNAME=root
DB_PASSWORD=

SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database

CACHE_STORE=database
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=belalhasan4470@gmail.com
MAIL_PASSWORD=hoheincjseufghfp
MAIL_ENCRYPTION=tls

MAIL_FROM_ADDRESS="belalhasan4470@gmail.com"
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"

JWT_SECRET=MxiphJ0vNlTH31EmpdFkTASxHekIJiC4krVA1UBfswl4rlcwpxoNWh58UIFQlzun

JWT_ALGO=HS256

BROADCAST_CONNECTION=pusher
PUSHER_APP_ID="2097550"
PUSHER_APP_KEY="c25c07128897a8a38698"
PUSHER_APP_SECRET="d437ea3f87d7eee34f4d"
PUSHER_APP_CLUSTER="ap2"

GOOGLE_CLIENT_ID=xxxxxxxx
GOOGLE_CLIENT_SECRET=xxxxxxxx
GOOGLE_REDIRECT_URI=http://localhost:8000/auth/google/callback

FACEBOOK_CLIENT_ID=xxxxxxxx
FACEBOOK_CLIENT_SECRET=xxxxxxxx
FACEBOOK_REDIRECT_URI=http://localhost:8000/auth/facebook/callback



 */
